# Generated by Django 5.2.4 on 2025-07-25 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UUID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='float1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ipadress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shift_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slarayDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timestarted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.AddField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
